export const allPartners = [
  {
    "id": "padie____336",
    "name": "PADIE - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image1.png",
    "password": "password123"
  },
  {
    "id": "crt____806",
    "name": "CRT - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image2.jpeg",
    "password": "password123"
  },
  {
    "id": "eaa____383",
    "name": "EAA - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "jat____50",
    "name": "JAT - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image3.jpg",
    "password": "password123"
  },
  {
    "id": "jve____453",
    "name": "JVE - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image4.jpeg",
    "password": "password123"
  },
  {
    "id": "pnje____856",
    "name": "PNJE - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image5.jpeg",
    "password": "password123"
  },
  {
    "id": "ong_alafia_999",
    "name": "ONG ALAFIA",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "https://alafia-togo.org/",
    "logo": "/partners/image6.jpeg",
    "password": "password123"
  },
  {
    "id": "colombe____785",
    "name": "COLOMBE - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "stadd____826",
    "name": "STADD - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image7.jpg",
    "password": "password123"
  },
  {
    "id": "ocdi_lom__organisation_de_la_c_699",
    "name": "OCDI Lomé Organisation de la Charité pour un Développement Intégral, Lomé",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image8.png",
    "password": "password123"
  },
  {
    "id": "wv____942",
    "name": "WV - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image9.jpg",
    "password": "password123"
  },
  {
    "id": "ong_fiadi_94",
    "name": "ONG FIADI",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image10.png",
    "password": "password123"
  },
  {
    "id": "ong_ahd_418",
    "name": "ONG AHD",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image11.jpeg",
    "password": "password123"
  },
  {
    "id": "ong_atape_690",
    "name": "ONG ATAPE",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "gircafem____319",
    "name": "GIRCAFEM - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "ong_jvs_32",
    "name": "ONG JVS",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "ovad_ap____427",
    "name": "OVAD-AP - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "odiae___d_v_loppememt_492",
    "name": "ODIAE - Dévéloppememt",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image12.jpg",
    "password": "password123"
  },
  {
    "id": "odjougbo____932",
    "name": "ODJOUGBO - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image13.jpeg",
    "password": "password123"
  },
  {
    "id": "sos_vita_995",
    "name": "SOS VITA",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image14.png",
    "password": "password123"
  },
  {
    "id": "jodd___oeuvrant_404",
    "name": "JODD - Oeuvrant",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image15.png",
    "password": "password123"
  },
  {
    "id": "ccdd___d_veloppement_449",
    "name": "CCDD - développement",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "ail____841",
    "name": "AIL - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image16.png",
    "password": "password123"
  },
  {
    "id": "ahead____226",
    "name": "AHEAD - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "adesco____524",
    "name": "ADESCO - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image17.jpg",
    "password": "password123"
  },
  {
    "id": "abad____966",
    "name": "ABAD - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image18.jpeg",
    "password": "password123"
  },
  {
    "id": "adiff___developpement_integral_433",
    "name": "ADIFF - Developpement Integral",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image19.jpg",
    "password": "password123"
  },
  {
    "id": "apss____713",
    "name": "APSS - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "card___developpement_405",
    "name": "CARD - Developpement",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "crt_rc____668",
    "name": "CRT-RC - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "dh____37",
    "name": "DH - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image20.png",
    "password": "password123"
  },
  {
    "id": "e_d___d_veloppement_555",
    "name": "E-D - Développement",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "pasdi_afrique_d_action_sociale_131",
    "name": "PASDI-Afrique d’Action Sociale",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image21.png",
    "password": "password123"
  },
  {
    "id": "2d____23",
    "name": "2D - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image22.jpeg",
    "password": "password123"
  },
  {
    "id": "raid____890",
    "name": "RAID - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "rp_rc___phast_181",
    "name": "RP/RC - Phast",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "ajt____225",
    "name": "AJT - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image23.png",
    "password": "password123"
  },
  {
    "id": "pades___economique_296",
    "name": "PADES - Economique",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image24.jpeg",
    "password": "password123"
  },
  {
    "id": "aprodife____104",
    "name": "APRODIFE - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image25.jpg",
    "password": "password123"
  },
  {
    "id": "cap_ejr___echo_838",
    "name": "CAP-EJR - Echo",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "ceapic___etudes_785",
    "name": "CEAPIC - Etudes",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "cdd___d_veloppemenet_853",
    "name": "CDD - Développemenet",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image26.jpeg",
    "password": "password123"
  },
  {
    "id": "3asc_____443",
    "name": "3ASC - :",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image27.jpg",
    "password": "password123"
  },
  {
    "id": "orepsa___regionale_631",
    "name": "OREPSA - Regionale",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image28.jpg",
    "password": "password123"
  },
  {
    "id": "jarc____792",
    "name": "JARC - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "",
    "password": "password123"
  },
  {
    "id": "capas____638",
    "name": "CAPAS - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image29.jpeg",
    "password": "password123"
  },
  {
    "id": "shd____576",
    "name": "SHD - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image30.jpg",
    "password": "password123"
  },
  {
    "id": "la_cde_309",
    "name": "La CDE",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image31.jpeg",
    "password": "password123"
  },
  {
    "id": "plan_international_togo_52",
    "name": "Plan International Togo",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image32.png",
    "password": "password123"
  },
  {
    "id": "seves___economiquement_459",
    "name": "SEVES - Economiquement",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image33.png",
    "password": "password123"
  },
  {
    "id": "hsf____974",
    "name": "HSF - ",
    "type": "national",
    "description": "Membre du réseau CCEABT",
    "email": "contact@cceabt.tg",
    "phone": "",
    "website": "",
    "logo": "/partners/image34.jpeg",
    "password": "password123"
  }
];